import React, { useState } from 'react';
import { View, TextInput, Button, Alert, StyleSheet } from 'react-native';
import { db } from '../firebase.js'; // Import the db object from firebase.js
import { ref, set, push } from 'firebase/database';

const SignInScreen = ({ navigation }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [username, setUsername] = useState('');
  const [signed, setSigned] = useState(false);

  const handleSignIn = async () => {
    try {
      Alert.alert('Success', `Welcome ${username}`);
      setSigned(true);

      // Generate a new key for the user in 'users'
      const newUserRef = push(ref(db, 'users'));

      // Get the key generated by push()
      const userId = newUserRef.key;

      // Prepare the new user object
      const newUser = {
        username: username,
        email: email,
        password: password, // Note: In production, hash the password before saving
        friends: [username], 
        moments: [], 
    };
  
      // Save the new user to the database under 'users/userId'
      await set(ref(db, `users/${userId}`), newUser);

      // Optionally navigate to another screen after successful sign-in
      navigation.navigate('Profile', { name: username });

    } catch (error) {
      const errorMessage = error.message;
      Alert.alert('Error', errorMessage);
    }
  };

  // Function to check if all inputs are filled
  const isFormValid = () => {
    return email.trim() !== '' && password.trim() !== '' && username.trim() !== '';
  };

  return (
    <View style={styles.container}>
      <TextInput
        placeholder="Email"
        onChangeText={setEmail}
        value={email}
        style={styles.input}
      />
      <TextInput
        placeholder="Password"
        onChangeText={setPassword}
        value={password}
        secureTextEntry
        style={styles.input}
      />
      <TextInput
        placeholder="Username"
        onChangeText={setUsername}
        value={username}
        style={styles.input}
      />
      <Button
        title="Sign In"
        onPress={handleSignIn}
        disabled={!isFormValid()} // Disable the button if the form is not valid
      />
      {username && signed && (
        <Button
          title={`Go to ${username}'s profile`}
          onPress={() => navigation.navigate('Profile', { name: username })}
        />
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 8,
  },
});

export default SignInScreen;
