import React, { useState } from 'react';
import { View, TextInput, Button, Alert } from 'react-native';
import { db } from '../firebase.js'; // Import the db object from firebase.js
import { ref, set, push } from 'firebase/database';

const SignInScreen = ({ navigation }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [username, setUsername] = useState('');
  const [signed, setSigned] = useState(false);

  const handleSignIn = async () => {
    try {
      Alert.alert('Success', `Welcome ${username}`);
      setSigned(true);

      // Generate a new key for the user in 'users'
      const newUserRef = push(ref(db, 'users'));

      // Get the key generated by push()
      const userId = newUserRef.key;

      // Prepare the new user object
      const newUser = {
        username: username,
        email: email,
        password: password, // Note: In production, hash the password before saving
      };

      // Save the new user to the database under 'users/userId'
      await set(ref(db, `users/${userId}`), newUser);

      // Optionally navigate to another screen after successful sign-in
      navigation.navigate('Profile', { name: username });

    } catch (error) {
      const errorMessage = error.message;
      Alert.alert('Error', errorMessage);
    }
  };

  return (
    <View>
      <TextInput
        placeholder="Email"
        onChangeText={setEmail}
        value={email}
      />
      <TextInput
        placeholder="Password"
        onChangeText={setPassword}
        value={password}
        secureTextEntry
      />
      <TextInput
        placeholder="Username"
        onChangeText={setUsername}
        value={username}
      />
      <Button
        title="Sign In"
        onPress={handleSignIn}
      />
      {username && signed && (
        <Button
          title={`Go to ${username}'s profile`}
          onPress={() => navigation.navigate('Profile', { name: username })}
        />
      )}
    </View>
  );
};

export default SignInScreen;
